### PR TITLE
Added operations for VALUES

### PR DESCRIPTION
**Pull request by GrazingScientist**
Hi @panmitz,

Since I use VALUES quite a lot, I missed them in this repo. It is not a complete implementation, but allows the definition of a single variable.

### CODE REVIEW

**Comment by GrazingScientist** [comment]
I just realize that I use an f-string for concatenation. Since this was introduced with Python 3.6, this PR is not backward-compatible.

Do you have a policy on that?

**Comment by panmitz** [comment]
> Hi @GrazingScientist , thanks for the contributions! I'd rather keep it backwards compatible if no critical issues demand the opposite. Cheers!

**Comment by GrazingScientist** [comment]
HI @panmitz,

okay! Thanks! Then I will fix it ASAP! :)

**Comment by GrazingScientist** [comment]
Okay! Fixed it! Hope it is fine this way! :)

Cheers,
Adrian

**Review by panmitz — APPROVED** [review]

**Pull request merged**
